# Generated by Django 3.1.7 on 2021-03-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='free', max_length=15, verbose_name='Status'),
        ),
    ]
